Catering/Pages/Create.cshtml.cs
using System;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Catering.Pages
{
    public class CreateModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;
        

        public CreateModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Restaurant Restaurant { get; init; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _dbContext.AddAsync(Restaurant);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Catering/Pages/Delete.cshtml.cs
using System;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;

        public DeleteModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [BindProperty] public Restaurant Restaurant { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            Restaurant = await _dbContext.RestaurantSet.SingleAsync(x => x.Id == id.Value);

            if (Restaurant is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(long? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            Restaurant = await _dbContext.RestaurantSet.SingleOrDefaultAsync(x => x.Id == id.Value);

            if (Restaurant is null)
            {
                return NotFound();
            }

            _dbContext.Remove(Restaurant);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Catering/Pages/DeleteMeal.cshtml.cs
using System;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class DeleteMealModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;

        public DeleteMealModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [BindProperty] public Meal Meal { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            Meal = await _dbContext.MealSet
                .Include(x => x.Restaurant)
                .SingleOrDefaultAsync(x => x.Id == id.Value);

            if (Meal is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(long id)
        {
            var meal = await _dbContext.MealSet.SingleOrDefaultAsync(x => x.Id == id);

            _dbContext.Remove(meal);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./details", new {id = meal.RestaurantId});
        }
    }
}

Catering/Pages/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;

        public DetailsModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        public Restaurant Restaurant { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            Restaurant = await _dbContext.RestaurantSet
                .Include(x => x.Meals)
                .SingleOrDefaultAsync(x => x.Id == id.Value);

            if (Restaurant is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddMealAsync(Meal meal)
        {
            var restaurant = await _dbContext.RestaurantSet
                .SingleAsync(x => x.Id == meal.RestaurantId);

            restaurant.AddMeal(meal);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./details", new {id = meal.RestaurantId});
        }
        
        public async Task<IActionResult> OnPostDeleteAsync(long mealId)
        {
            var meal = await _dbContext.MealSet.SingleOrDefaultAsync(x => x.Id == mealId);
            
            _dbContext.Remove(meal);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./details", new {id = meal.RestaurantId});
        }
    }
}

Catering/Pages/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class EditModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;


        public EditModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [BindProperty] public Restaurant Restaurant { get; set; }

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            Restaurant = await _dbContext.RestaurantSet
                .SingleOrDefaultAsync(x => x.Id == id.Value);

            if (Restaurant is null)
            {
                return NotFound();
            }

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // _context.Attach(RestaurantEntity).State = EntityState.Modified;

            try
            {
                _dbContext.Update(Restaurant);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await RestaurantExists(Restaurant.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private async Task<bool> RestaurantExists(long id)
        {
            return await _dbContext.RestaurantSet
                .SingleOrDefaultAsync(x => x.Id == id) is not null;
        }
    }
}

Catering/Pages/EditMeal.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class EditMealModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;


        public EditMealModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [BindProperty] public Meal Meal { get; set; }

        public async Task<ActionResult> OnGetAsync(long? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            Meal = await _dbContext.MealSet
                .Include(x => x.Restaurant)
                .SingleOrDefaultAsync(x => x.Id == id.Value);
            
            if (Meal is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<ActionResult> OnPostAsync()
        {
            _dbContext.Update(Meal);
            await _dbContext.SaveChangesAsync();
            return RedirectToPage($"./Details", new {id = Meal.RestaurantId});
        }
    }
}

Catering/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Catering.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Catering/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Catering.Domain;
using Catering.Infrastructure.DbContext;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Catering.Pages
{
    public class IndexModel : PageModel
    {
        private readonly SqlServerDbContext _dbContext;

        public IndexModel(SqlServerDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        public IList<Restaurant> Restaurants { get; set; }

        public async Task OnGetAsync()
        {
            Restaurants = await _dbContext.RestaurantSet
                .AsNoTracking()
                .ToListAsync();
        }
    }
}

Catering/Pages/Create.cshtml
@page
@model Catering.Pages.CreateModel


<h1>Restaurant</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Restaurant.Name" class="control-label"></label>
                <input asp-for="Restaurant.Name" class="form-control"/>
                <span asp-validation-for="Restaurant.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Catering/Pages/Delete.cshtml
@page
@model Catering.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Restaurant</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Restaurant.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Catering/Pages/DeleteMeal.cshtml
@page
@model Catering.Pages.DeleteMealModel

<h1>@Model.Meal.Restaurant.Name</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Meal.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Meal.Name)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" name="id" value="@Model.Meal.Id"/>
        <input type="submit" asp-page-handler="Delete" value="Delete" class="btn btn-danger"/> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Catering/Pages/Details.cshtml
@page
@model Catering.Pages.DetailsModel

<head>
    <link rel="stylesheet" href="~/css/star.css"/>
</head>

<h1>@Model.Restaurant.Name</h1>
<div>
    <hr/>
    <form method="post">

        <input type="hidden" name="meal.RestaurantId" value="@Model.Restaurant.Id">
        <label name="meal.Name">Name:</label><br>
        <input name="meal.Name"><br>

        <label name="meal.Score">Score:</label>
        <div class="rating">
            <input type="radio" id="star5" name="meal.Score" value="5" hidden/>
            <label for="star5"></label>
            <input type="radio" id="star4" name="meal.Score" value="4" hidden/>
            <label for="star4"></label>
            <input type="radio" id="star3" name="meal.Score" value="3" hidden/>
            <label for="star3"></label>
            <input type="radio" id="star2" name="meal.Score" value="2" hidden/>
            <label for="star2"></label>
            <input type="radio" id="star1" name="meal.Score" value="1" hidden/>
            <label for="star1"></label>
        </div>
        <label name="meal.Message">Message:</label><br>
        <input name="meal.Message">

        <button type="submit" asp-page-handler="AddMeal" onclick="location.reload();">Add</button>
    </form>
</div>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant.Meals.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant.Meals.First().Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant.Meals.First().Message)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Restaurant.Meals)
    {
        <tr>
            <td>
                @Html.DisplayFor(x => item.Name)
            </td>
            <td>
                @Html.DisplayFor(x => item.Score)
            </td>
            <td>
                @Html.DisplayFor(x => item.Message)
            </td>
            <td>
                <a asp-page="./EditMeal" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./DeleteMeal" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>


<div>
    <a asp-page="./Edit" asp-route-id="@Model.Restaurant.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Catering/Pages/Edit.cshtml
@page
@model Catering.Pages.EditModel

<h1>Restaurant</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Restaurant.Id"/>
            <div class="form-group">
                <label asp-for="Restaurant.Name" class="control-label"></label>
                <input asp-for="Restaurant.Name" class="form-control"/>
                <span asp-validation-for="Restaurant.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Catering/Pages/EditMeal.cshtml
@page
@model Catering.Pages.EditMealModel

<h1>@Model.Meal.Restaurant.Name</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Meal.Id"/>
            <input type="hidden" asp-for="Meal.RestaurantId"/>
            <div class="form-group">
                <label asp-for="Meal.Name" class="control-label"></label>
                <input asp-for="Meal.Name" class="form-control"/>
                <span asp-validation-for="Meal.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meal.Score" class="control-label"></label>
                <input asp-for="Meal.Score" class="form-control"/>
                <span asp-validation-for="Meal.Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meal.Message" class="control-label"></label>
                <input asp-for="Meal.Message" class="form-control"/>
                <span asp-validation-for="Meal.Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Catering/Pages/Index.cshtml
@page
@model Catering.Pages.IndexModel

<h1>Restaurant</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Restaurants[0].Name)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Restaurants)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>